# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-US"
title: "blep"
name: "Andrea Watson"
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Blep is an interactive cat food database with regularly updated 
  ingredient, macronutrient, and cost information for thousands of 
  cat food products, made easily accessible through flexible and 
  rapid filtering and sorting. It’s also the word for that thing 
  your pet does when they close their mouth without pulling their 
  tongue back in and it just kind of sticks out for a while.

url: watsonar.github.io
baseurl: /blep
repository: "watsonar/blep"

author:
  name: Andrea
  bio: "I have a bio"
  location: "Chicago, USA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github/watsonar"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/andrea-rose-watson/"
    - label: "Google Scholar"
      icon: "fas fa-bacterium"
      url: "https://scholar.google.com/citations?user=OoKiogwAAAAJ&hl=en"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.21.0"

# theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
